configuration:  
  projectName: eureka-server
  
server:
 port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery

  
spring:
  profiles: 192.168.12.103
eureka:
  instance:
    hostname: 192.168.12.103
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.12.104:8761/eureka/  
  server:
    enableSelfPreservation: false
      
---

spring:
  profiles: 192.168.12.104
eureka:
  instance:
    hostname: 192.168.12.104
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.12.103:8761/eureka/  
      
logging:
 file: Eureka.log
 level: INFO
  
