configuration:  
  projectName: eureka-server
  
server:
 port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery

  
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/  
  server:
    enableSelfPreservation: false
      
---

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/  
      
logging:
 file: Eureka.log
 level: INFO
  
