configuration:  
  projectName: eureka-server
  
server:
 port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
spring:
  profiles: localhost
eureka:
  instance:
    hostname: 192.168.12.103
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
      
---

spring:
  profiles: localhost1
eureka:
  instance:
    hostname: 192.168.12.104
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  
      
logging:
 file: Eureka.log
 level: INFO
  
