
configuration:  
  projectName: notification-service
#Bungalows Service Port
server:
 port: 8094
   
logging:
 file: Notification.log
 level: INFO
 
# MongoDB Properties 
spring:
 data:
  mongodb:
   dbuser: dofuser
   database: ForestDB
   password: g+H1ppDyrXldSwoLBo6c6Q==
   host: localhost
   port: 27017
   maxConnectionsPerHost: 10000
   threadsAllowedToBlockForConnectionMultiplier: 5
   serverSelectionTimeout: 30000
   maxWaitTime: 120000
   connectTimeout: 10000
   socketTimeout: 0
   socketKeepAlive: false
   sslEnabled: false
   sslInvalidHostNameAllowed: false
   alwaysUseMBeans: false 
   heartbeatFrequency: 10000
   minHeartbeatFrequency: 500
   heartbeatConnectTimeout: 20000
   heartbeatSocketTimeout: 20000
   localThreshold: 15
   cursorFinalizerEnabled: true
   
eureka:
  instance:
    preferIpAddress: true
    #leaseRenewalIntervalInSeconds: 1
    #leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
    #lease:
     # duration: 5
email:
  smtpserver: smtp.gmail.com
  smtpport: 465
  emailaddress: s.viboosha.g@gmail.com
  emailpassword: H25EQhbErFj/3bBSS/dK4A==
